name: Happy Day on the 8th day of the month

on:
  schedule:
    # æ¯æœˆ8ã®ã¤ãæ—¥ã®12:00(JST)ã«å‡¦ç†ã‚’å®Ÿè¡Œã™ã‚‹ã€‚
    # UTC ã® 03:00 ã¯ JST ã ã¨ 12:00 ã€‚
    - cron: '0 0 8,18,28 * *'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Happy Day!"
